### ISSUE TITLE
make a list of refactoring

### ISSUE THREAD

**Issue by icorson3** [icorson3/the_pivot#100]

**Comment by robbiejaeger** [comment]
Controllers:
- admin/orders controller has empty show method, necessary?
- vendors controller, index has where queries that can be moved to model

**Comment by robbiejaeger** [comment]
Views:
- admin/users/show could use partial(s)
- layouts/mailer(s), remove if not using mailer
- orders/show could maybe use a partial for the table
- user_mailer directory (using mailer?)
- shared/business_owner "See Orders" button could be more specific, confusing alongside other order history button
- shared/dashboard elsif statement has no condition
- shared/page_header there is a commented line of html (needed?)
- vendors/show partial for approval section?
- automatically show the user name when writing a review

**Comment by robbiejaeger** [comment]
- RETIRED VENDORS: custom route?
